# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'templates/calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import events
import datetime
import var
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(1, 2, 401, 301))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

class DialogCalendar(QtWidgets.QDialog):
    def __init__(self):
        super(DialogCalendar, self).__init__()
        # Definimos la variable global dlgcalendar como Ui_Dialog, que es la clase que crea qt desinger
        var.dlgcalendar = Ui_Dialog()
        # Inicializamos la interfaz
        var.dlgcalendar.setupUi(self)
        # Creamos variables para el día, més y año
        diaactual = datetime.datetime.now().day
        mesactual = datetime.datetime.now().month
        anoactual = datetime.datetime.now().year
        # Con el metodo setSelectedDate de calendarWidget, establecemos la fecha mostrada a la de hoy. Hay que pasarsela convertida a tipo QDate
        var.dlgcalendar.calendarWidget.setSelectedDate(QtCore.QDate(anoactual,mesactual,diaactual))
        # Hacemos que cuando se clickee sobre el, cargue la fecha al line edit con el método cargarFecha
        var.dlgcalendar.calendarWidget.clicked.connect(events.Eventos.cargarFecha)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
